spring:
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: "eastpeople@clinomics.co.kr"
    password: "eastman1"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true
        mime: UTF-8
        transport:
          protocol: smtp
  datasource:
    initialization-mode: always
  messages:
    basename: i18n/messages
    encoding: UTF-8
  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  security:
    user:
      name: user
      password: 1234
  thymeleaf:
    cache: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1024MB
datasource:
  seq:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://192.168.0.201:13306/seq_report?autoReconnect=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: clinomics
    password: uiop7890
  pdf:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://192.168.0.201:13306/seq_report?autoReconnect=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: clinomics
    password: uiop7890
seq:
  filePath: /BiO/Serve/seq_report
  tempFilePath: /BiO/Serve/seq_report/tempFiles
  workspacePath : /BiO/Serve/seq_report/workspace
  nodePath : node
  htmlToPdfPath : /BiO/Serve/html_to_pdf/index.js
externalApi: 
  url: https://api.genosolutiony.com/etc/
  tokenName: apiKey
  token: Sn4Wy4nlqmGEytAx5SkBXdhAp1LKYXXapc1hb6FG
titan:
  filePath: D:/BiO/Serve/seq_report/titan
  ftp:
    address: 192.168.0.238
    port: 21
    username: AFFXUSER
    password: affxpd
rest:
  http:
    auth-token-header-name: seqApiKey
    auth-token: fyhwp9e48fuq90p348yhtg09pq3874yhgt
logging:
  file: /BiO/Serve/seq_report/logs/seq_report.log
server:
  port: 9096